/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
llm-wiki-audit (Jonoka) — do not edit main.js directly; edit src/ then npm run build
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LlmWikiAuditPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/audit-core.js
var VALID_SEVERITIES = ["error", "warn", "suggest", "info"];
var SOURCE_PLUGIN = "obsidian-plugin";
var CONTEXT_MAX = 200;
function slugify(text, maxLen = 40) {
  const s = String(text || "").trim().toLowerCase().replace(/\s+/g, "-").replace(/[^\w\u4e00-\u9fff-]+/g, "").replace(/^-+|-+$/g, "").slice(0, maxLen);
  return s || "note";
}
function yamlEscape(s) {
  return '"' + String(s ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r/g, "").replace(/\n/g, "\\n") + '"';
}
function nowParts(d = /* @__PURE__ */ new Date()) {
  const pad = (n) => String(n).padStart(2, "0");
  const stamp = d.getFullYear() + pad(d.getMonth() + 1) + pad(d.getDate()) + "-" + pad(d.getHours()) + pad(d.getMinutes()) + pad(d.getSeconds());
  const offMin = -d.getTimezoneOffset();
  const sign = offMin >= 0 ? "+" : "-";
  const abs = Math.abs(offMin);
  const tz = sign + pad(Math.floor(abs / 60)) + ":" + pad(abs % 60);
  const created = d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate()) + "T" + pad(d.getHours()) + ":" + pad(d.getMinutes()) + ":" + pad(d.getSeconds()) + tz;
  const hex4 = Math.floor(Math.random() * 65536).toString(16).padStart(4, "0");
  return { stamp, created, hex4 };
}
function normalizeVaultPath(path) {
  return String(path || "").replace(/\\/g, "/").replace(/^\.\//, "");
}
function isAllowedWikiTarget(relPath) {
  const raw = String(relPath || "").replace(/\\/g, "/");
  if (raw.split("/").some((part) => !part || part === "." || part === "..")) return false;
  const p = normalizeVaultPath(raw);
  if (/^(?:\/|[A-Za-z]:\/)/.test(p)) return false;
  if (!p.toLowerCase().endsWith(".md")) return false;
  if (p.startsWith("audit/") || p.includes("/audit/")) return false;
  return p.startsWith("wiki/");
}
function lineRangeFromOffsets(fullText, from, to) {
  const start = Math.max(0, Math.min(from, fullText.length));
  const end = Math.max(start, Math.min(to, fullText.length));
  let line = 1;
  let startLine = 1;
  let endLine = 1;
  for (let i = 0; i < fullText.length; i++) {
    if (i === start) startLine = line;
    if (i < end && fullText[i] === "\n") {
    }
    if (i === end - 1 || end === start && i === start) endLine = line;
    if (fullText[i] === "\n") line++;
  }
  if (end === start) endLine = startLine;
  else {
    line = 1;
    for (let i = 0; i < end; i++) {
      if (i === end - 1) endLine = line;
      if (fullText[i] === "\n") line++;
    }
  }
  return [startLine, Math.max(startLine, endLine)];
}
function contextAround(fullText, from, to, max = CONTEXT_MAX) {
  const before = fullText.slice(Math.max(0, from - max), from);
  const after = fullText.slice(to, Math.min(fullText.length, to + max));
  return {
    anchor_before: before.slice(-max),
    anchor_after: after.slice(0, max)
  };
}
function buildAuditMarkdown(draft) {
  const target = normalizeVaultPath(draft.target || "");
  const anchor_text = draft.anchor_text ?? "";
  const comment = String(draft.comment || "").trim();
  const severity = draft.severity || "warn";
  const author = String(draft.author || "you").trim() || "you";
  const source = draft.source || SOURCE_PLUGIN;
  if (!anchor_text.trim()) return { ok: false, error: "empty_selection" };
  if (!comment) return { ok: false, error: "empty_comment" };
  if (!target) return { ok: false, error: "empty_target" };
  if (!isAllowedWikiTarget(target)) return { ok: false, error: "target_not_wiki_page" };
  if (!VALID_SEVERITIES.includes(severity)) return { ok: false, error: "bad_severity" };
  if (!["manual", "agent", "obsidian-plugin", "web-viewer"].includes(source)) {
    return { ok: false, error: "bad_source" };
  }
  const parts = nowParts(draft.now);
  const stamp = draft.stamp || parts.stamp;
  const created = draft.created || parts.created;
  const hex4 = draft.hex4 || parts.hex4;
  const id = `${stamp}-${hex4}`;
  const slug = slugify(comment || anchor_text);
  const filename = `${stamp}-${slug}.md`;
  const lines = draft.target_lines || [1, 1];
  const start = Math.max(1, Number(lines[0]) || 1);
  const end = Math.max(start, Number(lines[1]) || start);
  const before = String(draft.anchor_before ?? "").slice(-CONTEXT_MAX);
  const after = String(draft.anchor_after ?? "").slice(0, CONTEXT_MAX);
  const body = `---
id: ${id}
target: ${target}
target_lines: [${start}, ${end}]
anchor_before: ${yamlEscape(before)}
anchor_text: ${yamlEscape(anchor_text)}
anchor_after: ${yamlEscape(after)}
severity: ${severity}
author: ${author}
source: ${source}
created: ${created}
status: open
---

# Comment

${comment}

# Resolution

<!-- Filled when processed and moved to audit/resolved/ -->
`;
  return { ok: true, filename, body, id };
}
function processHint(relAuditPath, id) {
  const path = normalizeVaultPath(relAuditPath);
  if (id) {
    return `\u5904\u7406\u6279\u6CE8\uFF1A\u8BF7\u5904\u7406 open audit ${id}\uFF08${path}\uFF09\u3002`;
  }
  return `\u5904\u7406\u6279\u6CE8\uFF1A\u8BF7\u5904\u7406 open audit\uFF08${path}\uFF09\u3002`;
}

// src/main.ts
var DEFAULT_SETTINGS = {
  defaultAuthor: "you"
};
var LlmWikiAuditPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "add-audit-from-selection",
      name: "\u8BB0 llm-wiki \u6279\u6CE8\uFF08\u9009\u533A\uFF09",
      editorCallback: (editor, view) => {
        void this.beginAuditFromEditor(editor, view);
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, info) => {
        const view = info;
        menu.addItem((item) => {
          item.setTitle("\u8BB0 llm-wiki \u6279\u6CE8").setIcon("message-square-warning").onClick(() => {
            void this.beginAuditFromEditor(editor, view);
          });
        });
      })
    );
    this.addCommand({
      id: "copy-process-audits-hint",
      name: "\u590D\u5236\u300C\u5904\u7406\u6279\u6CE8\u300D\u63D0\u793A\u7ED9 Codex",
      callback: () => {
        const text = "\u5904\u7406\u6279\u6CE8";
        void navigator.clipboard.writeText(text).then(
          () => new import_obsidian.Notice("\u5DF2\u590D\u5236\uFF1A\u5904\u7406\u6279\u6CE8"),
          () => new import_obsidian.Notice(text)
        );
      }
    });
    this.addSettingTab(new LlmWikiAuditSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async beginAuditFromEditor(editor, view) {
    const file = view?.file;
    if (!file) {
      new import_obsidian.Notice("\u6CA1\u6709\u6253\u5F00\u7684 Markdown \u6587\u4EF6");
      return;
    }
    const selection = editor.getSelection();
    if (!selection || !selection.trim()) {
      new import_obsidian.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u6279\u6CE8\u7684\u539F\u6587");
      return;
    }
    const rel = normalizeVaultPath(file.path);
    if (!isAllowedWikiTarget(rel)) {
      new import_obsidian.Notice(`\u5F53\u524D\u6587\u4EF6\u4E0D\u662F\u5B89\u5168\u7684 wiki/*.md \u9875\u9762\uFF08${rel}\uFF09`);
      return;
    }
    if (!rel.toLowerCase().endsWith(".md")) {
      new import_obsidian.Notice("\u4EC5\u652F\u6301 Markdown \u6587\u4EF6");
      return;
    }
    if (rel.startsWith("audit/") || rel.includes("/audit/")) {
      new import_obsidian.Notice("\u4E0D\u8981\u5BF9 audit/ \u4E0B\u7684\u6587\u4EF6\u8BB0\u6279\u6CE8");
      return;
    }
    const fullText = editor.getValue();
    const from = editor.posToOffset(editor.getCursor("from"));
    const to = editor.posToOffset(editor.getCursor("to"));
    const target_lines = lineRangeFromOffsets(fullText, from, to);
    const ctx = contextAround(fullText, from, to);
    new AuditModal(this.app, {
      defaultAuthor: this.settings.defaultAuthor,
      selection,
      onSubmit: async (payload) => {
        await this.writeAudit({
          target: rel,
          anchor_text: selection,
          anchor_before: ctx.anchor_before,
          anchor_after: ctx.anchor_after,
          target_lines,
          severity: payload.severity,
          comment: payload.comment,
          author: payload.author
        });
      }
    }).open();
  }
  async writeAudit(input) {
    const built = buildAuditMarkdown({
      ...input,
      source: "obsidian-plugin"
    });
    if (!built.ok) {
      new import_obsidian.Notice(`\u65E0\u6CD5\u5199\u5165\uFF1A${built.error}`);
      return;
    }
    const folder = "audit";
    if (!await this.app.vault.adapter.exists(folder)) {
      await this.app.vault.createFolder(folder);
    }
    if (!await this.app.vault.adapter.exists("audit/resolved")) {
      try {
        await this.app.vault.createFolder("audit/resolved");
      } catch {
      }
    }
    let path = `${folder}/${built.filename}`;
    if (await this.app.vault.adapter.exists(path)) {
      path = `${folder}/${built.filename.replace(/\.md$/, "")}-${built.id.slice(-4)}.md`;
    }
    await this.app.vault.create(path, built.body);
    new import_obsidian.Notice(`\u5DF2\u8BB0\u5F55 open audit\uFF1A${path}`);
    const hint = processHint(path, built.id);
    void navigator.clipboard.writeText(hint).then(
      () => new import_obsidian.Notice("\u5DF2\u590D\u5236\u7ED9 Codex \u7684\u5904\u7406\u63D0\u793A"),
      () => void 0
    );
    const af = this.app.vault.getAbstractFileByPath(path);
    if (af instanceof import_obsidian.TFile) {
      await this.app.workspace.getLeaf(true).openFile(af);
    }
  }
};
var AuditModal = class extends import_obsidian.Modal {
  constructor(app, opts) {
    super(app);
    this.severity = "warn";
    this.comment = "";
    this.selection = opts.selection;
    this.defaultAuthor = opts.defaultAuthor;
    this.author = opts.defaultAuthor;
    this.onSubmit = opts.onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("llm-wiki-audit-modal");
    contentEl.createEl("h2", { text: "\u8BB0 llm-wiki \u6279\u6CE8" });
    contentEl.createEl("p", {
      text: "\u53EA\u5199\u5165 audit/ \u7684 open \u6587\u4EF6\uFF0C\u4E0D\u6539\u6B63\u6587\u3002\u5904\u7406\u65F6\u5BF9 Codex \u8BF4\u300C\u5904\u7406\u6279\u6CE8\u300D\u3002",
      cls: "llm-wiki-audit-hint"
    });
    contentEl.createEl("label", { text: "\u9009\u4E2D\u539F\u6587\uFF08anchor_text\uFF09" });
    const sel = contentEl.createEl("textarea", { cls: "llm-wiki-audit-selection" });
    sel.value = this.selection;
    sel.readOnly = true;
    sel.rows = 4;
    new import_obsidian.Setting(contentEl).setName("severity").addDropdown((dd) => {
      for (const s of VALID_SEVERITIES) {
        dd.addOption(s, s);
      }
      dd.setValue(this.severity);
      dd.onChange((v) => {
        this.severity = v;
      });
    });
    new import_obsidian.Setting(contentEl).setName("author").addText((t) => {
      t.setValue(this.author);
      t.onChange((v) => {
        this.author = v;
      });
    });
    contentEl.createEl("label", { text: "Comment\uFF08\u7EA0\u9519\u8BF4\u660E\uFF09" });
    const commentEl = contentEl.createEl("textarea", { cls: "llm-wiki-audit-comment" });
    commentEl.rows = 4;
    commentEl.placeholder = "\u5B9E\u9645\u5E94\u4E3A\u2026\uFF1B\u4F9D\u636E\u2026";
    commentEl.addEventListener("input", () => {
      this.comment = commentEl.value;
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u53D6\u6D88").onClick(() => this.close());
    }).addButton((btn) => {
      btn.setButtonText("\u5199\u5165 audit/").setCta().onClick(() => {
        void (async () => {
          this.comment = commentEl.value;
          if (!this.comment.trim()) {
            new import_obsidian.Notice("\u8BF7\u586B\u5199 Comment");
            return;
          }
          await this.onSubmit({
            severity: this.severity,
            comment: this.comment.trim(),
            author: this.author.trim() || this.defaultAuthor
          });
          this.close();
        })();
      });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var LlmWikiAuditSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "llm-wiki Audit" });
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4 author").setDesc("\u5199\u5165 frontmatter.author").addText((t) => {
      t.setValue(this.plugin.settings.defaultAuthor);
      t.onChange(async (v) => {
        this.plugin.settings.defaultAuthor = v || "you";
        await this.plugin.saveSettings();
      });
    });
  }
};
